{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-configmap
data:
    {{- range $key, $val := .Values.env.normal }} 
    {{ $key }}: {{ $val | quote }}
    {{- end }}
{{- end }}
