{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
data:
    {{- range $key, $val := .Values.env.secret }} 
    {{ $key }}: {{ $val | quote | b64enc }}
    {{- end }}
{{- end }}